### ISSUE TITLE
No dark theme when comming from firefox awesomebar or enter devdocs.io directly

### ISSUE THREAD

**Issue by danbruegge** [Thibaut/devdocs#211]
Hi,

there is no dark theme when i enter:
* devdocs directly with http://devdocs.io/
* devdocs from firefox awesomebar with my keyword "dd" but also with other keywords

After reloading the page, the dark theme appears except the startpage.

The same will work in chrome.

Firefox version is 38.0.1 but also it appears in older versions. My OS, Archlinux.

// Edit
Also when i'm on the startpage, the light theme is on. Then i hit the toggle button to use the dark theme and reload the page the light theme is back.

**Comment by Thibaut** [comment]
I use Firefox too and it works for me.
- Do you have cookies enabled?
- What does `app.AppCache.isEnabled()` give you in the web console?

**Comment by danbruegge** [comment]
Ok, don't know why but enable cookies explicit for devdocs.io is working.

Usually, i accept cookies from sites, except third-party cookies.

After hitting the Globe on the url-bar > "more information" > "Permissions" and "Use cookies: allow" it will work with the dark theme.

**Comment by Thibaut** [comment]
Here's how my Firefox is set up:

![preferences 2015-05-27 07-43-31](https://cloud.githubusercontent.com/assets/17579/7835096/1d57aec6-0444-11e5-9e3b-370f0100bf55.png)

It all works for me. The cookie lives on the same domain (`devdocs.io`).

It could be that your awesome bar is set up with https://devdocs.io/ instead of http://devdocs.io/?

Closing the issue as I don't think there's anything I can do on DevDocs's side to fix this.

**Comment by danbruegge** [comment]
I've removed and add devdocs.io and now it runs with http://. 

I never accept third-party cookies. After setting the third-party cookie to "from visited" devdocs will set the cookie for the dark theme. So i think here is the problem.

Currently for me it is ok to set manually the cookie settings for devdocs.io.
