### ISSUE TITLE
Desktop app

### ISSUE THREAD

**Issue by mansona** [Thibaut/devdocs#230]
Hey Folks, 

I was just wondering if there are any plans to package this app as a desktop app using something like NW.js? I would imagine you wouldn't need to implement any of the server component in the application as it could just communicate with the http://devdocs.io/ "api" directly. 

For the record i'm not asking for this feature, I'm just wondering if it has been talked about at all before I go and do a proof of concept and find that it doesn't work or it's against the ethos of the project or something :wink:

**Comment by Thibaut** [comment]
See #39.

I'm not against the idea but have no interest in working on this myself. The web app is fully functional offline so I don't see much benefit to a desktop app, with the exception of a task/menu bar app that brings up the web app.

>  I would imagine you wouldn't need to implement any of the server component in the application as it could just communicate with the http://devdocs.io/ "api" directly. 

DevDocs doesn't have an API. The search is done entirely in the browser. That's why it's fast no matter how slow your internet connection is :)

The web app gets metadata to use for the search (name/path of functions, etc.), then loads the pages from the CDN (or IndexedDB, if you've downloaded the doc for offline access).

**Comment by Thibaut** [comment]
Closing this since I have no intention of making a desktop app at this time. If someone wants to, and there is something I can do to help, feel free to open a new issue or email the [mailing list](https://groups.google.com/forum/#!forum/devdocs).

**Comment by igauravsehrawat** [comment]
@Thibaut Just to let you know, there is an desktop app for devdocs. https://github.com/egoist/devdocs-app

**Comment by Thibaut** [comment]
@igauravsehrawat Saw that. I linked to it here: http://devdocs.io/about#plugins
