### ISSUE TITLE
IndexedDB not support on my Android 4.1.2 device (native playstore app)

### ISSUE THREAD

**Issue by extdevelopment** [Thibaut/devdocs#238]
I would like to ask, can you help what can i do.

How to identify which browser you are running with devDocs on my device?
Firefox for Android, Opera Android up to date.

thx

**Comment by busches** [comment]
Per http://caniuse.com/#feat=indexeddb the lastest Firefox, Chrome, and Opera mobile all support IndexDB. I'd confirm the version you're using is the latest.

**Comment by extdevelopment** [comment]
IndexDB in mobile browser with https://devdocs.io/  page works fine. (Firefox for Android)

But i installed "native" app from play store, and i would like to use offline mode.
Native app wrote error IndexedDB not support in my browser.

**Comment by Thibaut** [comment]
Hey guys,
There isn't much I can do here. DevDocs tries to use IndexedDB when it's available, otherwise it shows the error page. There's no "user-agent sniffing" going on.
This means that Android's embedded browser likely isn't the same as Chrome/Firefox for Android, and doesn't support IndexedDB at this time.
Hopefully Google will fix that in a future version of Android.

**Comment by laukstein** [comment]
You can add old Android support with _IndexedDB polyfill over WebSQL_ https://github.com/axemclion/IndexedDBShim, https://www.npmjs.com/package/cordova-plugin-indexeddb-async. Keep in mind WebSQL is dropped from spec.

Based on [caniuse...sql-storage.json#L214](https://github.com/Fyrd/caniuse/blob/1c13358ba79fa3ce1453be4afe1f13089126888b/features-json/sql-storage.json#L214) seems supported since Android 2.1, except:
> Reported to not be supported on the Samsung-based Android 4.

**Comment by Thibaut** [comment]
If you're using the app from the play store, please uninstall it. It's made by someone who is using (and profiting from) the name DevDocs without permission. If you install the app via Chrome (visit [devdocs.io](http://devdocs.io) and select "Add to home screen"), the offline mode will work fine and there'll be no ads.

> You can add old Android support with IndexedDB polyfill over WebSQL

I'd rather not import a large and complex dependency like this (which means bugs and extra maintenance), when most browsers support IndexedDB already.

**Comment by laukstein** [comment]
@Thibaut, thanks for suggestion! I agree with on avoiding outdated frameworks, dropped specs, etc.

I just tested on Android 4.0.4 noticed crashes https://github.com/Thibaut/devdocs/issues/411.

**Comment by marrokin** [comment]
Error devdocs.io/offline

Configuración básica de la aplicación
-------------------------------------

Nombre: Firefox
Versión: 48.0.2
ID de compilación: 20160823121617
Canal de actualización: release
Agente de usuario: Mozilla/5.0 (Windows NT 6.1; rv:48.0) Gecko/20100101 Firefox/48.0
OS: Windows_NT 6.1 x86
Ventanas multiproceso: 0/2 (Deshabilitado por los complementos)
Modo seguro: false


[Image Error](http://image.prntscr.com/image/3cc0a4a425804e3d8b66c7ab5502f36b.png)
