### ISSUE TITLE
Search misses [pushState]

### ISSUE THREAD

**Issue by martine** [Thibaut/devdocs#260]
Searching for pushState produces no results.

There's a DOM History node (http://devdocs.io/dom/history) and from there you can see pushState documented but the function itself is not in the index.

**Comment by Thibaut** [comment]
I'll fix this up in a future update.

**Comment by martine** [comment]
If you don't have time to work on it and you think you could sketch out the
basic approach to fixing it here I would be happy to try to fix it myself.

brevity due to phone

**Comment by Thibaut** [comment]
@martine Thanks for offering to help. The fix is basically just to re-run the scraper, since it looks like MDN has started creating these pages since the last time I ran it:
https://developer.mozilla.org/en-US/docs/Web/API/history/pushState
(but not https://developer.mozilla.org/en-US/docs/Web/API/history/replaceState)
It takes a bit of time to scrape MDN and update the files. I'll do it in the next week or two.

**Comment by Thibaut** [comment]
Done (ded6daa94c4644a5c972aee9f0b77b0eb6f3dc3e).
