### ISSUE TITLE
Add ability to hide deprecated methods/functions/etc.

### ISSUE THREAD

**Issue by JesseTG** [Thibaut/devdocs#261]
Would be especially valuable for the HTML docs.

**Comment by Thibaut** [comment]
Each doc highlights deprecated functions differently. I'd rather leave it to them to do the job than maintain "deprecated" lists in DevDocs, sorry.

**Comment by JesseTG** [comment]
Who says you have to maintain it?  We already have perfectly good parsers that can be modified to figure it out for us, don't we?

**Comment by Thibaut** [comment]
> that can be modified to figure it out for us

This code will need to be written and maintained across docs and updates.

I don't want to make DevDocs more time-consuming to maintain unless there is a significant benefit to be had by most users at the end. Since most docs like MDN already do a good job of highlighting deprecated functions (MDN puts a big red banner at the top), I don't think the benefit of implementing such a feature in DevDocs will be useful to most users, sorry.

**Comment by JesseTG** [comment]
This isn't about *highlighting* deprecated functions; this is about the opposite.  Taking some noise out of the signal, so I don't have to dodge descriptions of deprecated HTML attributes whenever I'm doing web dev.

**Comment by Thibaut** [comment]
That doesn't change the fact that one has to know what these functions are in order to hide them. 

If you care strongly about this, feel free to fork the repo and run the app locally.

**Comment by JesseTG** [comment]
If I or someone else were to actually implement this (even for just one set of docs, on a provisional/prototypical basis), would you consider merging it in?

**Comment by Thibaut** [comment]
Sorry but no. There will inevitably be a maintenance cost, and I don't want to clutter the codebase with  half-implemented/experimental features.

In any case, I disagree that hiding deprecated functions would be useful to most users. If we make it a user setting (which the UI currently doesn't support), people will forget that they enabled it and be confused when they search a function that has recently been deprecated and no results show up.
