### ISSUE TITLE
Enhanced search incorporating the docs content

### ISSUE THREAD

**Issue by flekschas** [Thibaut/devdocs#272]
I'd be very much looking forward to a more advanced _Google-like_ search. As DevDocs's vision say:

> DevDocs aims to make reading and **searching reference documentation fast**, easy and enjoyable.

one major goal is to provide a way of finding things fast but currently the search seems to be limited to the title of a doc. For example, when I select AngularJS's docs and search for _promise_ I expect to find the docs relating to $q but nothing related shows up even though the actual page describing $q mentions the word _promise_ 108 times. Moreover, searching for _q_ leads to no results at all! Actually, searching for _a_ returns the desired page about `$q`. I know implementing this isn't trivial but it would be extremely useful.

In general, keep the good work up! Really nice app.

**Comment by Thibaut** [comment]
> Moreover, searching for q leads to no results at all! Actually, searching for a returns the desired page about `$q`

This is a weird bug. I'll try to fix it soon.

> currently the search seems to be limited to the title of a doc.

As you said this isn't trivial. The search is done completely client-side, which is why DevDocs is fast, free (no expensive servers needed), and works offline.

The README also says that "the project doesn't intend to compete with full-text search engines". This is still my position today. I can only work on DevDocs on my spare time, which is not enough to implement such major changes, sorry.
