### ISSUE TITLE
Use AppCache fallback entry to support URLs when offline

### ISSUE THREAD

**Issue by binki** [Thibaut/devdocs#276]
The Offline docs state:

> Note that loading any page other than [devdocs.io](http://devdocs.io) directly won't work (due to limitations in AppCache).

You could have the following in your appcache manifest:

    FALLBACK:
    / /

Then, when the user tries to navigate to a URI such as http://devdocs.io/css/@charset by typing directly into the URI bar or the browser being launched by an external program, the fallback would be used and devdocs could have code in the normal index page to load the correct data. I assume that devdocs.org is just sending the user the normal page anyway.

The possible gotchas here should just be that if devdocs is trying to load data through AJAX the AJAX request might get the fallback page rather than the requested data—if the user is offline and the AJAX request should have failed anyway.

Supporting launching directly to a particular documentation page when in offline mode would make the offline experience even more seemless than it already is.

Another though, if AJAX-fetched resources are only at certain namespaces anyway, would be to do the following:

    NETWORK:
    /ajax
    /static
    
    FALLBACK:
    / /

If I’m understanding how appcache works correctly, this would make most users launching to a particular URI fetch it directly from appcache rather than trying to load it directly from the website first. When the browser is not able to access the Internet, this would eliminate a timeout in trying to fetch the documentation URI from the browser. When the browser is able to access the internet, this will prevent the browser from making a (small) number of superfluous requests to the server.

Thoughts?

**Comment by Thibaut** [comment]
Thanks for investigating this.

I can't enable app cache beyond the root page because (1) each page would end up in the cache, leading to an ever increasing cache (app cache constraint), and (2) the app runs in different modes when loading from the root vs. another page (so that external links to docs that the user hasn't yet enabled still work).

You can, however, load and search any page when offline like this:
http://devdocs.io/#/css/@charset
http://devdocs.io/#q=test

**Comment by binki** [comment]
> (1) each page would end up in the cache, leading to an ever increasing cache (app cache constraint)

As long as the document you use for the fallback entry doesn’t have a `manifest` attribute, and it doesn’t now, then the cache shouldn’t arbitrarily increase in size.

> (2) the app runs in different modes when loading from the root vs. another page (so that external links to docs that the user hasn't yet enabled still work).

If you look at the [appcache fetch algorithm](http://www.w3.org/TR/html5/browsers.html#changesToNetworkingModel), you’ll see that putting a URI namespace in the fallback section attempts to access the internet before loading the fallback entry. If `/` is listed as a namespace which should get the fallback document when the internet is inaccessible, that should not prevent attempts to load resources from online-only docsets. It just provides a way to serve to the user your special directly-linked mode page without the user having to be connected to the internet.

> You can, however, load and search any page when offline like this:
> http://devdocs.io/#/css/@charset
> http://devdocs.io/#q=test

Then why redirect the user to non-hash URIs? If the user browsed the whole site through hash URIs in the first place, this whole issue would be skirted ;-). The user should not need to manually edit bookmark URIs, for example, or have to edit the URIs of about restored tabs.

My point is that appcache has the capability to enable direct navigation while the user is offline even with your current URI scheme. Why not take advantage of it?

**Comment by Thibaut** [comment]
> If you look at the appcache fetch algorithm, you’ll see that putting a URI namespace in the fallback section attempts to access the internet before loading the fallback entry. If / is listed as a namespace which should get the fallback document when the internet is inaccessible, that should not prevent attempts to load resources from online-only docsets.

TIL, thanks. a0ea89ff45a0ff73e5eab980de119982d1ae2b21

> Then why redirect the user to non-hash URIs?

Because http://devdocs.io/css/@charset is guaranteed to show you the doc even if you haven't enabled it (e.g. you clicked a link on StackOverflow). This works by comparing the request path with the "docs" cookie on the server, and returning a different page (single doc vs. full app) depending on if the doc is enabled or not.

http://devdocs.io/#/css/@charset, on the other hand, will fail if the doc is disabled, since the `#hash` part of the URL isn't sent to the server, and the root path will only load docs that you've enabled (for performance reasons — DevDocs has 100k entries, the app would be much slower if it loaded all of them all the time).

**Comment by binki** [comment]
> TIL, thanks. a0ea89f

Thanks, that appears to work!

> http://devdocs.io/#/css/@charset, on the other hand, will fail if the doc is disabled

Ah, so right now it will not try to dynamically load the CSS docset when it sees `css` in the hash.

**Comment by Thibaut** [comment]
I had to revert because external redirects like http://devdocs.io/s/jetbrains stopped working, even after I whitelisted them (a10bec01e48ff74d629807b59f1a693470ff8a09; works in Chrome but not Firefox).

I'll see if I can change those links to use a subdomain in the coming weeks, so we can bring back the fallback.

**Comment by Thibaut** [comment]
Done (aad0063653a4b03869c353b4f24ae862199c8edb ac2cbdd82287f0b67180ddbab919d041dbf2d0cb)
