### ISSUE TITLE
Clarification on procedure for adding new documentation

### ISSUE THREAD

**Issue by sandmanSam** [Thibaut/devdocs#277]
In the "Contributing Guidelines" under "Requesting new documentation" it states to NOT open a new issue to request documentation, and to instead vote on external site Trello.Then, under the "contributing new documentations" section, it states to "Please open an issue before adding a new documentation".  

I've seen numerous replies on issues in this repo for documentation requests with just 2 links back to the "contributing" guidelines and external site Trello but no clarification on correct procedure for adding documentation.  Does the vote on Trello have to reach a certain amount of votes before documentation can be added?  Is there an "approved documentation to be added" queue on Trello that has to be accepted before new documentation can be added or can anyone submit a PR with new documentation?  On Trello, it says "DevDocs is open source -- the fastest way to see a documentation is to contribute" but I am unsure if documentation can be contributed before it is "voted" on, or can anyone submit a PR with new documentation.  Thank you for your assistance.

**Comment by Thibaut** [comment]
> I've seen numerous replies on issues in this repo for documentation requests with just 2 links back to the "contributing" guidelines and external site Trello but no clarification on correct procedure for adding documentation.

The Contributing Guidelines are asking that you open an issue if you're actively working on adding a new documentation, so that multiple people don't work on the same doc at the same time. If you're not working on it (as was the case in all these issues), then you should use Trello. Otherwise we'll end up with as many GitHub issues as we have Trello cards.

I'll remove the sentence that asks to open an issue when working on a doc, to avoid the confusion.

>  Does the vote on Trello have to reach a certain amount of votes before documentation can be added?

No, but the doc should be reasonably popular (i.e. don't submit your personal/just-launched projects until they've gotten some traction).

>  Is there an "approved documentation to be added" queue on Trello that has to be accepted before new documentation can be added?

No, but better check with me first (GitHub issue or email).

Thanks
