### ISSUE TITLE
Sandbox variables into window scope

### ISSUE THREAD

**Issue by srgraham** [Thibaut/devdocs#284]
This may be only useful with JS library documentation, but I'd like to have window.jQuery be set to the jQuery variable when I'm looking at jQuery documentation or window._ be set to a lodash variable when checking out lodash documentation. I tend to test out features using chrome dev console when looking at documentation, but when using devdocs.io, those variables are not loaded, so are not accessible from the window scope.

An alternative would be to have a sandbox area that expands into view when you click a button, that loads those variables when you click it and it just acts like the regular dev tools console.

**Comment by Thibaut** [comment]
Thanks for the suggestion. Doing this for all JS libraries would be too hard to maintain (I only work on DevDocs on my spare time), and like you said we couldn't inject them in the global scope because it would conflict with DevDocs's own JS. However, if you create such a JS sandbox I'd be happy to link to it or integrate it in DevDocs.
