### ISSUE TITLE
Add Dojo documentation to DevDocs

### ISSUE THREAD

**Issue by ShaneQful** [Thibaut/devdocs#291]
Just wanted to make you aware as per the [contributer guidelines](https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md) that I'm going to start on a scraper for the dojo documentation. If it works out I'll probably try add dijit as well.

**Comment by ShaneQful** [comment]
Closing this as I've opened a pull request https://github.com/Thibaut/devdocs/pull/293

**Comment by jamime** [comment]
Thank you for adding this. Dojox and Dijit would also be nice.

**Comment by ShaneQful** [comment]
I'll have a look this weekend if I get the time should be pretty simple to add them although I don't know if dojox is relevant enough ...

**Comment by Thibaut** [comment]
It's easy to add Dojox and Dijit (just remove [this](https://github.com/Thibaut/devdocs/blob/5de8c37258348821bc70337fa52dba6af6bd4711/lib/docs/scrapers/dojo.rb#L27)). The problem is that it makes the doc massive (30k+ entries). This will have a negative impact on the search (slower) and offline mode (higher chance to go over the browser's quota).

Are there large chunks of Dojox and Dijit we can ignore / aren't useful to most people?

**Comment by ShaneQful** [comment]
Dojox is the experimental part of dojo bits of it are useful but for the most part people steer clear because it's difficult to tell what bits are maintained and what bits aren't.

Dijit is dojo's widget library, this is actually heavily used but it's depends on the developer's usage. Most of the projects I'ved worked on for instance, we only used the framework to build our own widgets along with one or two of the more common widgets like the dialog.
