### ISSUE TITLE
CSS properties also include data types

### ISSUE THREAD

**Issue by Siilwyn** [Thibaut/devdocs#330]
For example `mq-boolean` shows up in the properties list while the value is a data type. Not sure, but this might have to do with links that redirect...
https://developer.mozilla.org/en-US/docs/Web/CSS/mq-boolean

**Comment by Thibaut** [comment]
Indeed it's because of the redirection. I'll remove the page in the next run. Thanks for reporting the bug.

**Comment by Siilwyn** [comment]
No problem @Thibaut, does this need some kind of change in the code? If so, I could create a PR though I'm not sure where the code is located that handles this.

**Comment by Siilwyn** [comment]
With this update the `type` of a CSS document is 'gone'. In the sense that you can't see if something is a property, value, selector or function. The current `type` looks to have categories rather than what kind of thing it is. Would be nice to be able to browse them by type too, or atleast include the `type` as meta data.

Don't get me wrong @Thibaut I use DevDocs almost every day and I really appreciate your work.

**Comment by Thibaut** [comment]
@Siilwyn This was suggested in #302. If you can think of a better way to organize the CSS docs, please reply there. The app/UI doesn't support multiple types per document, so we can't have it both ways. This could change in the future but is not on my short-term roadmap.

IMO the new categories are a bit more useful, since it's usually pretty easy to infer whether it's a property, value, function, etc. from the name (functions have `()`, data types have `<>`, pseudo elements have `:`, etc.).

> I use DevDocs almost every day and I really appreciate your work.

:+1: :heart:
