### ISSUE TITLE
Resizing document list in Firefox is broken

### ISSUE THREAD

**Issue by mikonieminen** [Thibaut/devdocs#354]
When trying to resize document list in the left, it does not work when using Firefox.

Observed using Firefox 44.0.1 under Ubuntu 15.10.

**Comment by Kaijiro** [comment]
Are you in dual screen mode ?

**Comment by Thibaut** [comment]
The functionality is only broken when Firefox is running [e10s](https://wiki.mozilla.org/Electrolysis). Mozilla started an A/B test not long ago, enabling e10s for some users. I reported the issue here: https://bugzilla.mozilla.org/show_bug.cgi?id=1244533 but we may as well implement a work-around in DevDocs if we can. I'll look at #355 over the week-end (thanks).

**Comment by Thibaut** [comment]
Fixed by #355 1a04656d1165c3daad31e1cd35a844b581105fe5 183a616b0321e06ab7b31e765454932fd4080e1e
