### ISSUE TITLE
repl

### ISSUE THREAD

**Issue by iofjuupasli** [Thibaut/devdocs#363]
E.g. I can go to http://ramdajs.com/docs/
open devtools (in chrome) and play with library, try different things, very quickly, and starting from copying examples from docs.

I do the same on https://rpominov.github.io/kefir/

And I find it extremely useful to quickly check code snippets

It would be nice to make it possible on http://devdocs.io/

Some libraries can conflict, so probably better solution would be adding repl right on page with only one library included.

**Comment by PombaM** [comment]
I think what you are requesting is beyond the scope that was intended by @Thibaut but then, i am speaking for myself not the author.

**Comment by iofjuupasli** [comment]
@PombaM I think the scope for devdocs is to provide information about code. What can be better for understanding code than quickly trying to code?
I understand that it isn't simple to implement, and there are troubles with versioning, dependencies, repl integration, and probably more. But I think it can be long-term improvement that will make devdocs closer to the single and complete source of data about popular libraries.

**Comment by PombaM** [comment]
@iofjuupasli  jsfiddle.net, jsbin.com, babeljs.io/repl might be handy! :neutral_face:

**Comment by iofjuupasli** [comment]
@PombaM docs.angularjs.org facebook.github.io/react/docs lodash.com/docs ramdajs.com/docs

**Comment by Thibaut** [comment]
I agree this could be useful but the cost is very high, for what I think amounts to a small benefit (if you're reading a doc, chances are you're already running the library in your app).

- due to conflicts, we couldn't inject the scripts in the main window (can't unload JS after it's been loaded, and on DevDocs you never reload the page)
- an alternative would be to inject the scripts in an iframe, but then it's a lot less user-friendly
- it would add significant maintenance overhead (to keep everything working & up-to-date)

For those reasons, this isn't something I'm interested in adding to DevDocs, sorry (maintaining the app is already very time-consuming, and I only have my spare time to do it).
