### ISSUE TITLE
Chrome App in dedicated window

### ISSUE THREAD

**Issue by katoquro** [Thibaut/devdocs#366]
Feature request.
There is a feature when you can launch chrome app in dedicated window (like [google keep](https://chrome.google.com/webstore/detail/google-keep-notes-and-lis/hmjkmjkepdijhoojdojkdfohbdgmmhki)). Chrome provides support for different OSs so you can launch it like a native app.

If Chrome app starts in a new window you can avoid additional searching of particular tab with app and you can navigate through the windows easily.

**Comment by Styrke** [comment]
You don't need a Chrome app to do this.

Here's how to do it on Windows:
1. Go to DevDocs in Chrome.
2. Open *Hamburger menu* > *More tools* > *Add to desktop...*
3. Make sure to check the *Open as window* option.

**Comment by katoquro** [comment]
Hm, this doesn't work on mac os :(
![image](https://cloud.githubusercontent.com/assets/1694937/13527411/d0cc7f18-e21f-11e5-8920-0639e6097fb9.png)

And there are no such options 
![image](https://cloud.githubusercontent.com/assets/1694937/13527472/2f6f9c12-e220-11e5-8290-fb8bc9541c9c.png)

my chrome is 
```
Google Chrome	49.0.2623.75 (Official Build) (64-bit)
Revision	76745cbfbdac04e2fe3204f8b4f96ae7dc6bfcfa-refs/branch-heads/2623@{#561}
OS	Mac OS X 
Blink	537.36 (@76745cbfbdac04e2fe3204f8b4f96ae7dc6bfcfa)
JavaScript	V8 4.9.385.28
Flash	20.0.0.306
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36
```

**Comment by Thibaut** [comment]
Enable this in `chrome://flags` to add the "Open as window" option:

![chrome flags 2016-03-05 12-41-29](https://cloud.githubusercontent.com/assets/17579/13549257/d336fda4-e2cf-11e5-8dc0-9f32c0603a07.png)

**Comment by katoquro** [comment]
Interesting, why can some applications be opened in a window w/o hacks?
btw using of especial flag from menu with a huge warning doesn't look like a right way but this workaround works!

**Comment by Thibaut** [comment]
Sorry I should have explained before closing. I don't know why Chrome doesn't turn that option "on" by default. Probably because it's still experimental / not completely stable. Hopefully they'll enable it for everyone soon.

Apps that work without the option are "packaged" apps. DevDocs is a "hosted" app. Packaged apps are built specifically for Chrome, whereas hosted apps are just website shortcuts.

Making DevDocs a packaged app would require rewriting a big chunk of the JS without [these APIs](https://developer.chrome.com/apps/app_deprecated), and then maintaining two codebases (because the web app can't do without Chrome's disabled APIs). This isn't something I'm interested in doing, sorry.
