### ISSUE TITLE
Laravel docs' anchor links not working

### ISSUE THREAD

**Issue by gbdematos** [Thibaut/devdocs#377]
Guides' anchor links aren't working.

Example:
http://devdocs.io/laravel/docs/5.2/structure#introduction

Also, is it possible to separate the website docs (Guide), and the files docs (which are just docblocs)?
Most of the time I want to search just the Guide, but it shows a lot of results from files.

And it would be very nice to have the anchor links displayed as "submenus".

Example:

Now: 
Guides > Application Structure
Guides > Authorization

Better (using just Guides):
Application Structure > Introduction
Application Structure > The Root Directory
Authorization > Defining Abilities
Etc...

**Comment by Thibaut** [comment]
> Also, is it possible to separate the website docs (Guide), and the files docs (which are just docblocs)?

DevDocs is more about reference & API docs than guides & tutorials, because the latter is harder to index (needs full-text search, which Google will always be better at than DevDocs). So I prefer not to create sub-entries for guides & tutorials. You can always use `ctrl/cmd+f` to search within a page.

Hope that makes sense. Thanks for the bug report.
