### ISSUE TITLE
Provide option for one-off tips to support devdocs

### ISSUE THREAD

**Issue by bfishman** [Thibaut/devdocs#395]
Hello!  I find myself using devdocs.io all the time, and decided I wanted to support your work. Unfortunately the only option to do so at the moment is gratipay, which supports recurring tips only. I understand the motivation behind their model, but honestly don't want to start a recurring payment and have one more thing to track mentally. 

Perhaps I'm in the minority, but this may be 'turning off' other would-be donators for similar reasons. In the interest of earning yourself some more $$, would you consider adding another means for donation?

In any case, awesome work. Not to mention the uber functionality of the site, the aesthetic and subtle design features are exquisite. Thanks for what you've done!

**Comment by Thibaut** [comment]
Hey!

Thanks a lot for your kind words and wanting to donate. I'm glad DevDocs is useful to you.

Accepting donations is tricky (accounting/tax-wise), so at the moment I only accept Gratipay, and don't wish to receive one-time donations via, e.g., PayPal. But if you (or someone else) know of a service that facilitates accepting one-time donations, I'd be happy to try it.

Otherwise, sending a thank you note like you did and spreading the word about DevDocs is a great way to support the project :)

**Comment by igauravsehrawat** [comment]
> But if you (or someone else) know of a service that facilitates accepting one-time donations, I'd be happy to try it.

How about Stripe? Or amazon wishlist?

Problem with Gratipay is that it only accepts credit card(which I don't want to give).

Cheers

**Comment by Thibaut** [comment]
@igauravsehrawat I've been considering switching to Patreon. They're also recurring-only (so they need to store your credit card info somewhere), but using [Stripe](https://patreon.zendesk.com/hc/en-us/articles/203913779-Do-you-store-my-credit-card-information-). Would that work for you?

**Comment by igauravsehrawat** [comment]
@Thibaut  So sorry, got of my mind, totally.
Patreon accepts Paypal too, which is fine. Stripe would do too.
Again. Sorry for late reply.
