### ISSUE TITLE
21Mb package Install crashes on Android 4.0.4

### ISSUE THREAD

**Issue by laukstein** [Thibaut/devdocs#411]
Fallowing the suggestion "Add to home screen" https://github.com/Thibaut/devdocs/issues/238#issuecomment-222006086

I just tested on Android 4.0.4, and it allowed to Install Offline data for all "default package" (CSS, HTML, JavaScript, etc.) except DOM (21.9Mb). On Install it it crashes (shows "Aw, Snap!" screen), perhaps exceeds offline limit. The same would happen if I would try to Install PHP (21.4 Mb).
Resource http://www.html5rocks.com/en/tutorials/offline/quota-research/ (might be outdated).

For better UX, I think it would be better instead to handle IndexedDB limit and show warning. Maybe splitting the "packages" to smaller sizes and Installing one after another would avoid this crash.

**Comment by Thibaut** [comment]
Unfortunately there is currently no way to programmatically detect how much storage is available in IndexedDB, or even how much is being used. Once the quota is exceeded IndexedDB throws an error and the only thing the app can do is delete the database and start over :/

This might be because in most browsers the quota is based on the amount of free space on the device, which is always changing. There's a [spec](https://storage.spec.whatwg.org/) being worked on to help with this but it seems pretty far off.

However, the fact that you're seeing the "Aw, Snap!" screen is a different issue. This means the browser crashed, and browsers should never crash. Please report the bug in the [Chrome bug tracker](https://bugs.chromium.org/p/chromium/issues/list). Not much I can do from DevDocs's side.
