### ISSUE TITLE
Add Download summary for offline installation

### ISSUE THREAD

**Issue by Nosthertus** [Thibaut/devdocs#433]
It is always useful to know how much data it's going to be downloaded when installing/updating docs

This could help developers that uses mobile data bandwidth as they have to be careful with it

**Comment by Thibaut** [comment]
Aren't these two things enough?

![devdocs - offline 2016-07-09 11-07-13](https://cloud.githubusercontent.com/assets/17579/16708535/61583046-45c5-11e6-88fa-acaa57fcf057.png)

You can disable automatic updates and then see how much data will be downloaded before you install/update (it's actually a lot less since the numbers in that table are before GZIP).

**Comment by Nosthertus** [comment]
It could be, but just giving suggestion, it happens to me when i'm connected through mobile network and i  have to take care of the bandwidth i use, also it would take me time to calculate the summary if there are many installs/update

**Comment by Thibaut** [comment]
Thanks for the suggestion. I'd recommend downloading/updating docs while on a Wi-Fi network. The use-case you describe doesn't warrant making the offline table more complex IMHO.
