### ISSUE TITLE
UX: Paging using cursor-keys

### ISSUE THREAD

**Issue by Lewiscowles1986** [Thibaut/devdocs#453]
When I go to any doc that is longer than a single screen, I cannot page using cursor keys as I normally would. Whilst it is fantastic that you allow cursor-keys in the menu visually (it looks great). 

 * I'd sooner be able to use the content than address a niche of navigating the side-bar with cursor keys
 * I'm quite sure users that cannot see the screen would not be able to access the documentation if they cannot use the keyboard

I Have included a screen-recording in ogv format from recordmydesktop

[dev-docs-io-scrolling.zip](https://github.com/Thibaut/devdocs/files/404910/dev-docs-io-scrolling.zip)

**Comment by Thibaut** [comment]
Hi - Thanks for the feedback. You can use Alt+Up/Down or Space/Shift+Space to scroll the main content area.

I want DevDocs to be usable without a mouse. Since the sidebar and search are the primary ways to browse content, I prefer to use the arrow keys to navigate the sidebar. There is a feature request to swap the behavior of Up/Down and Alt+Up/Down [here](https://github.com/Thibaut/devdocs/issues/296).
