### ISSUE TITLE
Sticker language+Tab behavior

### ISSUE THREAD

**Issue by nyarly** [Thibaut/devdocs#493]
Having started "single language mode" with e.g. "Rust<Tab>", it'd be nice if the [Rust] language marker in the search box were harder to clobber - currently holding Backspace to clear a previous search will delete it as if it were a single character. Removing the language filter with a keystroke would be nice, but I generally want to leave the language search "locked" while I'm working and wish it weren't so easy to revert to "all docs"

**Comment by Thibaut** [comment]
Thanks for the suggestion. I think making backspace not clear the search scope when the search field is empty would be confusing/annoying to the average user. IMO it's the expected behavior.

There are already multiple ways to clear the search field without resetting the scope:

- using `alt+backspace` / `cmd+backspace` on OS X (probably similar keyboard shortcuts exist on Windows/Linux — let me know if not)
- by clicking the "X" icon (which can be focused/activated by hitting `tab`)
