### ISSUE TITLE
Unable to search within documentation page (Django)

### ISSUE THREAD

**Issue by dev169** [Thibaut/devdocs#502]
Hello and thanks for the great work!

I've enabled the documentation for Django 1.10, and I'm typing, for example, `ALLOWED_HOSTS` in the search field. Unfortunately nothing is coming up, even though this can be found by manually locating `http://devdocs.io/django~1.10/ref/settings` after typing `settings`. 

Is this an overall limitation of the devdocs.io search functionality or a specific issue with the Django docs indexing? I'm thinking the latter, since in Python 3 I'm able to search for stuff that doesn't have their own page, like `str.split`.

Help?

**Comment by Thibaut** [comment]
Hi

Every entry in DevDocs's index is manually indexed (as in there is code in the scraper that goes look for it). It's not like Google where you can just search anything and it'll find anything (that wouldn't work offline in a browser). So as you said it's primarily a limitation of the DevDocs search.

However, in this case it should be possible to index the headings on that page so that each becomes an entry in the search index. The trick is to index only the headings that should appear in the search index (things like "Introduction", "Overview", etc. should not). I'll try to do that next time I update the Django docs.

Thanks for the feedback.

**Comment by dev169** [comment]
Thank you for the detailed and informative reply. Any improvements welcome.
