### ISSUE TITLE
can we include the terminal commands to devdocs?

### ISSUE THREAD

**Issue by tommygebru** [Thibaut/devdocs#505]
I would love to see some Command Line documentation on devdocs.io especially offline 👍

**Comment by phumberdroz** [comment]
I also wanted to write a similar Issue, what is about adding cheat cheats in general? 
Like Atom, Sublime Shortcuts? Or Reg Ex snippets?

**Comment by tommygebru** [comment]
Oh yeah thats very nice! editors and Regular Expressions!!!

**Comment by Thibaut** [comment]
You can suggest new documentations here: https://trello.com/b/6BmTulfx/devdocs-documentation
DevDocs isn't in the business of writing docs, so we'd need to find a good source that allows its docs to be modified and redistributed.

**Comment by JesseTG** [comment]
@Thibaut Why not just the `man` pages?

**Comment by Thibaut** [comment]
@JesseTG if only it was that simple :P There are 100,000s of man pages. Adding all of them to DevDocs would make the search unusable. There are also different man pages for different OSs. But the biggest hurdle is that DevDocs currently only supports scraping HTML, and I'm not aware of any man pages documentation that can be downloaded in HTML format and freely redistributed.

**Comment by JesseTG** [comment]
@Thibaut So get choosy.  I see several different approaches in that:

- Stick with major packages like [coreutils](https://www.gnu.org/software/coreutils/manual/html_node/index.html), [grep](https://www.gnu.org/manual/blurbs.html), or similar.
- Don't do the man pages themselves, but look at the projects that the `man` page belongs to; maybe they have more thorough documentation that you can pull from.
- Or just stick with [whatever GNU provides](https://www.gnu.org/software/software.html) for now; they offer a *lot* of command-line tools.  I get the feeling that requests for "command line docs" are really requests for "GNU software" (since a large part of the Unix ecosystem is shaped by them).

**Comment by Thibaut** [comment]
@JesseTG that's more work than I can handle right now. Contributions welcome.
