### ISSUE TITLE
Add Meta:http-equiv="X-UA-Compatible" to the head

### ISSUE THREAD

**Issue by FelixRilling** [Thibaut/devdocs#520]
Adding
```html
<meta http-equiv="X-UA-Compatible" content="IE=edge">
```
To the head would ensure that the page displays correctly in Internet Explorer and Edge

**Comment by Thibaut** [comment]
Document modes are [deprecated as of IE11](https://blogs.msdn.microsoft.com/ie/2014/11/11/living-on-the-edge-our-next-step-in-helping-the-web-just-work/). DevDocs renders perfectly fine for me in Edge. A recent change broke IE11, which I just fixed in 09e4407bafb64e771ad002c39d137f721f76b6b4. Make sure you haven't turned on compatibility view.
