### ISSUE TITLE
[feature] Disable option for documentation that has been enabled

### ISSUE THREAD

**Issue by dotnetCarpenter** [Thibaut/devdocs#523]
Over time I have enabled a lot of libraries. I would like to be able to cleanup my list without reseting everything.
I propose a _disable_ feature.

![devdocs](https://cloud.githubusercontent.com/assets/43763/19854338/36abd4f6-9f4d-11e6-8276-9da5b58b37d4.png)

**Comment by Thibaut** [comment]
You can do that by clicking "Select documentation" at the bottom of the sidebar, unchecking all the docs you don't want anymore, then clicking Save. It won't reset anything.

I figure people enable docs more often than they disable them, which is why I added a shortcut for enabling. Doing the same for disabling would add clutter to the UI for too small a benefit, IMO.

**Comment by Thibaut** [comment]
Oh and the app needs to do a full reload to properly disable docs, whereas docs can be enabled on the fly. It would be annoying if the "Disable" links were to do a full reload.
