### ISSUE TITLE
Consider using LZ compression for localStorage

### ISSUE THREAD

**Issue by tophf** [Thibaut/devdocs#525]
The supersmall (5kB) and superfast [lz-string](https://github.com/pieroxy/lz-string/) library compresses data stored by devdocs.io in localStorage to 14% of its original size as tested here with 8 docs activated: 1980kB vs 267kB.

**Comment by Thibaut** [comment]
DevDocs uses `localStorage` simply as an extra cache for the index files, on top of AppCache, to make the app boot as quickly as possible. If `localStorage` is full, there is little impact on performance, and offline availability is still complete (because the index files are also in AppCache, which acts as a fallback for any index file that the app doesn't find in `localStorage`).

So compressing the data would yield little benefit (a couple MBs of storage on the device), but at the cost of a slower app, since no matter how fast lz-string is, it'll still take quite a bit of CPU to uncompress all this data (which happens at a critical time: when the app boots).

Compressing the offline data stored in `IndexedDB` (content of the docs) would yield more benefit, as this data can amount to 10s of MBs, but again performance would take a hit (when opening docs). In my opinion, performance is more important than storage space, as the amount of storage the app uses is pretty small in comparison to other apps, and speed is key to the UX / usability of the app.
