### ISSUE TITLE
Saving disabled documentations offline

### ISSUE THREAD

**Issue by Nateowami** [Thibaut/devdocs#535]
In order to save a documentation offline you have to enable it. However, I want to save lots of documentations I don't frequently use so I'll have access them even without internet. If you enable a documentation, save it offline, and then disable it, it is deleted. It seems that enabling documentation should be about searching it, and should not directly relate to whether it is saved offline. I can see why it was done this way though, as it does make the UI simpler.

Slightly related to #336, "Add a feature to export/import offline data."

EDIT: The fact that you can selectively search just a single documentation is quite helpful here and perhaps makes this not worth changing. I'd used the feature in the past but forgot it was an available. So while it would still be nice, feel free to close this as unplanned.

**Comment by Thibaut** [comment]
Thanks for the feedback.

It would make the UI and code a lot more complex to support this. Since it's pretty edge case (the vast majority of users probably wouldn't use it), I don't think this is something worth adding. 

If you want to have a backup of various docs that you rarely use, I'd recommend [setting up DevDocs locally](https://github.com/Thibaut/devdocs#quick-start). You won't get automatic updates, but it might save you one day if you're offline and want to access a doc you didn't enable on devdocs.io.
