### ISSUE TITLE
Page missing `https://devdocs.io/javascript/global_objects/date/tolocaleformat`

### ISSUE THREAD

**Issue by amingilani** [Thibaut/devdocs#572]
[Javascript Date](https://devdocs.io/javascript/global_objects/date) has a reference to the `Date.prototype.toLocaleFormat()` which links to a non-existent page at `https://devdocs.io/javascript/global_objects/date/tolocaleformat`.

<img width="835" alt="screen shot 2017-01-23 at 11 23 01 pm" src="https://cloud.githubusercontent.com/assets/1188552/22216991/19ef8e4e-e1c3-11e6-80d4-b9e965aad537.png">

<img width="521" alt="screen shot 2017-01-23 at 11 22 01 pm" src="https://cloud.githubusercontent.com/assets/1188552/22217012/2e01f3a4-e1c3-11e6-8465-e4a7acfb3c8d.png">

**Comment by Thibaut** [comment]
This is because DevDocs skips pages that have the following banner:

![date prototype tolocaleformat - javascript mdn 2017-02-05 17-20-42](https://cloud.githubusercontent.com/assets/17579/22630395/7a0561f6-ebc7-11e6-956a-5fe87e6df034.png)


https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleFormat

I'll fix the link (so it opens MDN) in a future update.
