### ISSUE TITLE
Tokenizer Functions missing in PHP doc

### ISSUE THREAD

**Issue by jhdxr** [Thibaut/devdocs#598]
it seems that http://php.net/manual/en/ref.tokenizer.php is missing in devdocs. for example,
http://php.net/manual/en/function.token-get-all.php
http://devdocs.io/#q=token_get_all

**Comment by jhdxr** [comment]
btw, I found http://php.net/manual/en/function.is-numeric.php is missing in the devdocs as well.
but what surprised me most is that I can find http://devdocs.io/php/function.is-numeric in my history, which means this entry was present in devdocs, and it has been removed for some reason/problem.

**Comment by Thibaut** [comment]
Thanks for the feedback. The Tokenizer functions will be added in the next update. The PHP doc is tricky to scrape because it contains so much and isn't organized very well. If you notice anything else of value that's missing, let me know.

> btw, I found http://php.net/manual/en/function.is-numeric.php is missing in the devdocs as well.
but what surprised me most is that I can find http://devdocs.io/php/function.is-numeric in my history, which means this entry was present in devdocs, and it has been removed for some reason/problem.

http://devdocs.io/php/function.is-numeric works for me. What do you see when you open that URL?

**Comment by jhdxr** [comment]
http://devdocs.io/php/function.is-numeric works for me now. I'll take a screenshot if I run into this problem next time. Thank you for your hard work.
