### ISSUE TITLE
Appending dash in search doesn't work

### ISSUE THREAD

**Issue by japborst** [Thibaut/devdocs#600]
Small bug:
When searching, appending a dash "-" doesn't show results. Example:
In the git documentation there is a function `git filter-branch`. Searching for `filter` or `filter-b` shows the function, but `filter-` shows nothing.

**Comment by codymaust** [comment]
Adding this for information

This looks like the relevant line
https://github.com/Thibaut/devdocs/blob/master/assets/javascripts/app/searcher.coffee#L132 

The dash/hyphen is replaced with a dot "."

You can confirm this by searching for ```git filter.``` , which shows a match for ```git filter-branch```

![image](https://cloud.githubusercontent.com/assets/1775342/24202160/abca6a12-0ee8-11e7-93da-c878ef46cc15.png)

**Comment by japborst** [comment]
Yeah searching with a dot works beautifully. Is there any reason the dashes should be replaced by dots?

**Comment by Thibaut** [comment]
> Is there any reason the dashes should be replaced by dots?

There is. The search uses a bunch of heuristics to efficiently rank results. Among other things, the [ranking algo](https://github.com/Thibaut/devdocs/blob/44ade1865ee9292e18e41662a782328c3cbbb3e6/assets/javascripts/app/searcher.coffee#L34-L74) looks at the presence/position of "separators" (`.`, `#`, etc.) in the matching string relative to the search query, to give higher scores to results like `document.head`, over `Headers`, when searching for `head` — thereby greatly improving the search results. For performance reasons, all "separators" are replaced by dots in the search strings/queries, so that all "separators" are just one and the same character (this makes the search orders of magnitude faster).

Dashes are considered "separators" so that results like `linear-gradient()` rank higher than `CanvasGradient` when searching for `gradient`. However, dashes are only considered "separators" when they're followed by a word character, so that searching for `-` doesn't match everything. As you can see, in-browser search is hard/tricky science 😛 

I have a fix in 9d919591c2fd739a972cea02b47421df41e5c183.

**Comment by japborst** [comment]
Ah I see. That is actually super interesting stuff! Did you come up with the heuristic yourself? I must admit that the search works really well as the desired functions are always at the top of the query results.

**Comment by Thibaut** [comment]
@japborst I did. Disclaimer: I have no formal education on search algorithms, so I may have missed some easy/better solution 😛

Search results are quite difficult to optimize (improving one type of search may degrade others). If you've got feedback on the quality of search results, feel free to open new issues.
