### ISSUE TITLE
Add option to use native scrollbars

### ISSUE THREAD

**Issue by mika76** [Thibaut/devdocs#601]
Currently the scrollbars are thin and look nice, but when searching something on the page in Chrome, the found items are not shown in the scrollbar like in native Chrome.

**Comment by Thibaut** [comment]
Thanks for the feedback. I added a setting to force native scrollbars on Webkit/Blink. However, this won't fix your issue, because Chrome only supports "showing search items on the scrollbar" on the `<body>` scrollbar. For various reasons DevDocs uses a custom scroll container. Maybe Chrome will add support for custom scroll containers in the future.

**Comment by mika76** [comment]
Aw that's too bad - it's such a nice and useful feature. Thanks anyway.
