### ISSUE TITLE
Make menu open only on click

### ISSUE THREAD

**Issue by mika76** [Thibaut/devdocs#603]
Could you please make the devdocs menu (next to the search bar) open only when clicked? I find it keeps popping open when all I want to do is hover over the search and it's just distracting...

**Comment by prashcr** [comment]
Is there a particular reason for hovering over the search bar?

**Comment by mika76** [comment]
Pretty standard use case for a menu top open only on click. 

What I meant above is that whenever I want to go to the search bar or even the first item or two in the list I hover over the menu by mistake and then it pops open and then I have to move off it just so that it closes so I can continue with what I was doing.

**Comment by prashcr** [comment]
Fair point, I only use the keyboard shortcuts so that didn't bother me. I guess it's up to the maintainer.

**Comment by Thibaut** [comment]
I set it to open on hover because I felt it would make the menu more discoverable, which is always an issue when "hiding" navigation behind an icon/button.

It's on my list to make some UI tweaks. I'll re-evaluate this then.

Note that you don't need to click the search field to focus it. Pressing any alphanumeric key, backspace, or escape, will focus it automatically.

**Comment by mika76** [comment]
@Thibaut Thanks for considering it
