### ISSUE TITLE
Any chance to support IntelliJ or JetBrains platform as a whole?

### ISSUE THREAD

**Issue by Kimi-Arthur** [Thibaut/devdocs#608]
There is a plugin for Dash [here](https://plugins.jetbrains.com/plugin/7351-dash), which improves the experience quite a lot as it can construct the query with context, providing potentially more accurate result.

Just wonder whether there will be a similar plugin for devdocs. Thanks!

**Comment by Kaijiro** [comment]
Hi,

As @Thibaut said in [#133](https://github.com/Thibaut/devdocs/issues/133), it isn't in his short-terms priority and furthermore it means that he should create an API, which is not planned at all for now.

Therefore the only answer I can give you now (but maybe Thibaut would be more precise than me), is maybe, but don't expect it for now :)

**Comment by Thibaut** [comment]
There exists plugins for [Sublime Text](https://packagecontrol.io/packages/DevDocs), [Atom](https://atom.io/packages/devdocs), [etc.](https://github.com/search?q=topic%3Adevdocs&type=Repositories) None were made by me, as I don't have the time to make/maintain plugins in addition to maintaining DevDocs.

I welcome people making DevDocs plugins and I'm happy to make changes to the app to facilitate them + add a link on [here](http://devdocs.io/about#plugins).  

Closing the issue, since I have no plans to make an IntelliJ/JetBrains plugin myself.
