### ISSUE TITLE
Add CTRL+N and CTRL+P to move between selections

### ISSUE THREAD

**Issue by ryanlewis** [Thibaut/devdocs#617]
CTRL+N and CTRL+P are the vim shortcuts for selecting word completion, but has become universal enough that it is used in quite a number of places (at least on mac). For example, you can scroll through the autocompetions on Chrome's Omnibar using these shortcuts.

**Comment by j-f1** [comment]
<kbd>Ctrl</kbd>+<kbd>N</kbd> and <kbd>Ctrl</kbd>+<kbd>P</kbd> are already taken by the browser, and I don’t think they can be overridden.

**Comment by ryanlewis** [comment]
This might be a OS-specific thing - for example, those shortcuts are implemented by Github on repository pages and work on both Chrome and Safari on MacOS. I concede this is probably a different situation on windows however.

**Comment by Thibaut** [comment]
Why not use the up/down arrow keys? I find those a lot more convenient.

**Comment by ryanlewis** [comment]
I concede that most would agree, but many others use the shortcuts above in other apps (or any from vim world)

In my case, the shortcuts are nearer the home row and where the hand naturally lies on a keyboard, and my workstation is a laptop with tiny arrow keys.

**Comment by Thibaut** [comment]
`ctrl+n` / `ctrl+p` on macOS are used for moving the cursor to the beginning/end of a text field. Since in DevDocs the search field (is intentionally) almost always focused, I don't think we should override the OS's default behavior.

Closing this, but happy to consider other shortcuts if you have suggestions.

**Comment by Kache** [comment]
What about `ctrl+f` and `ctrl+b`?

I'd also suggest `alt+f` and `alt+b` but `alt+f` is "focus first link" for some reason, when browsers already have a general way of doing that.

> Why not use the up/down arrow keys? I find those a lot more convenient.

Prefer to keep my hands at home row, rather than feeling for arrow keys then feeling back for typing again.

**Comment by Kache** [comment]
What about `ctrl+u`/`ctrl+d`?

Unfortunately for `f`/`b`, `alt+f` is "focus first link" for some reason, when browsers already have a general way of doing that.

> Why not use the up/down arrow keys? I find those a lot more convenient.

Prefer to keep my hands at home row, rather than feeling for arrow keys then feeling back for typing again.

Tbh I don't really like the "all letter keys focus search box" b/c it means a lot of potential commands aren't possible. An example of how this clashes is `space` is supposed to scroll the content screen, but it conflicts with typing a space in the search bar. It's quite annoying -- I'll probably submit an issue about that one if I don't find an existing one.
