### ISSUE TITLE
TOC for Erlang sometimes not working

### ISSUE THREAD

**Issue by qwfy** [Thibaut/devdocs#626]
If you type `gen_server:call` in the search box in the sidebar, and click `gen_server:call/2`, it won't take you to the corresponding documentation as you might expect, but if you click `gen_server:call/3`, you will be taken to the correct one.

This bug is very consistent, I think it's because the way the Erlang documentation is organized, in Erlang, function with the same name but different arity are considered different, but in practice, you often use them do similar things, **so they are often documented together** (like `gen_server:call/2` and `gen_server:call/3`).

**Comment by Thibaut** [comment]
Thanks for the bug report.

I made it so only one entry per function is indexed and removed the arity from the name, since in practice I don't think it's very useful, and it adds duplicate results in the search.

Also found another issue (missing entries) and made a bunch of other improvements to the doc (added syntax highlighting). Let me know if anything else can be improved.

**Comment by qwfy** [comment]
can confirm it works. thanks for the fix :+1:
