### ISSUE TITLE
Show images offline

### ISSUE THREAD

**Issue by j-f1** [Thibaut/devdocs#633]
Currently, images are directly referenced in documentations. Unfortunately, this causes them to not show up when the device is offline. One possibility would be to transform the image URLs into data: urls for the offline download.

**Comment by Thibaut** [comment]
Using data URIs is a great idea. This would also solve the problem of insecure assets over HTTPS, which is preventing me from making HTTPS the default (some docs have images pointing to HTTP origins).

It may significantly increase the size of a few docs, and make some pages slower (data URIs are loaded synchronously and can cause UI lag), but I think that's OK / manageable.

The main hurdle is that the scraper isn't built in a way that makes doing something like this easy. HTTP requests are made concurrently, but the scraping process is single-threaded, with each page processed in succession by the main thread. As things stand, downloading images as part of the processing of each page would have to be done in a blocking/synchronous manner (preventing other pages from being processed while each image is downloaded one after the other), which would be inefficient. But maybe that's good enough, since few docs have images.

I'll look into this more when I have time. Thanks for the feedback.

**Comment by j-f1** [comment]
@Thibaut What if, instead of using `data:` URIs, the scraper listed all of the images it encountered and then the links get rendered to the cache manifest?

**Comment by Thibaut** [comment]
Again very cool idea. In practice I think it would make the code a lot more complex though. We'd need to pass the information down from the scraper all the way to the frontend. Also, the app cache manifest is updated often; caching all the images there would make those updates a lot slower.

I also don't want to couple more functionality to app cache, as it's going away (will be replaced by service worker once Webkit supports it).

**Comment by Thibaut** [comment]
This took some work but I think I finally got it to work. The first documentation I scrapped with images converted to data URIs had images that were very un-optimized, so I quickly realized we'd need to optimize the images, or some docs would become unnecessarily big. This lead to memory corruption issues (content of pages getting randomly mixed up) when running the image optimizer, which — fingers crossed — I tracked down to an HTTP pipelining issue in cURL or Typhoeus/Ethon (the wrapper gem).

The image optimization slows down scrapping, but I think it's a good tradeoff given that it gives us offline support for images, and fixes "mixed content" issues, which should allow us to finally switch to HTTPS by default (still some work to be done for this to happen, though).

Images bigger than a certain size (~120KB) are kept as external URLs, to avoid massive docs. From what I've seen so far, those big images are usually screenshots that aren't very important (the scrapping process will log every image it skips, and the max size can be increased per-documentation).

Over the coming months, all docs will get their images inlined / offline-enabled (as I update them).

Thanks again for the idea.
