### ISSUE TITLE
Mobile version: some shortcuts does not work

### ISSUE THREAD

**Issue by suricactus** [Thibaut/devdocs#638]
I'm using Vivaldi web browser with web panels, which request mobile version by default:
`"Mozilla/5.0 (Linux; Android 6.0.1; SM-G920F Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.90 Mobile Safari/537.36 Vivaldi/1.91.867.38"`

However when I hit `/` devdocs.io site does not focus the search field. What is more, when I search, I can't navigate the results by arrow keys.

Is it intentionally to block keyboard shortcuts on mobile devices?

**Comment by Thibaut** [comment]
Thanks for the feedback. Keyboard shortcuts should work as expected on mobile now. The only remaining difference is that the search field won't be auto-focused, because this triggers the popup keyboard on iOS &co, which makes the app unusable. But if you hit `/` or any alphanumeric key, the search field should now focus automatically.
