### ISSUE TITLE
Add enzyme 

### ISSUE THREAD

**Issue by FDiskas** [Thibaut/devdocs#694]
Please add enzyme documentation
http://airbnb.io/enzyme/

**Comment by FDiskas** [comment]
And @Thibaut no comments? :round_pushpin:

**Comment by Kaijiro** [comment]
As you didn't respect the [Contribution Guideline for requesting new documentations](https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations) Thibaut closed your issue. There is nothing to add because when you open the issue, there is a comment stating that you must not open an issue for requesting new documentations.

Thibaut and I (and sometimes other people) are answering tens of this kind of issues by week, this is why sometimes Thibaut does not bother answering.

**Comment by Kaijiro** [comment]
We thought that people would read the template issue and see that they were doing something wrong.

Anyway, this is a good tip, thank you for the advice.

**Comment by FDiskas** [comment]
Year, and you should add some link in about section

**Comment by Thibaut** [comment]
@j-f1 @Kaijiro to be honest after adding the issue template, I kinda lost patience with these issues.

![new issue thibaut-devdocs 2017-10-05 17-17-10](https://user-images.githubusercontent.com/17579/32144598-70d01ff4-bc91-11e7-89aa-3a2852909d28.png)

Thanks for the tip, though. I'll consider using a saved reply next time.
