### ISSUE TITLE
[ FEATURE ] sync settings using Chrome (?)

### ISSUE THREAD

**Issue by comatory** [Thibaut/devdocs#707]
Not sure if this can be supported out-of-the box. However what I'm missing is this:

I often switch between two workstations, both have devdocs.io added in Chrome. It would be cool if the settings could be synced between the clients (enabled/disabled documentation, auto-download for documentation marked to be available offfline).

I'm still bit hazy what devdocs really is, this could probably be done if it was "real" Chrome app but it's just a web with capabilites for offline user right? (PWA).

**Comment by j-f1** [comment]
There’s an export button inside the preferences, which will let you download your enabled documentations and other settings, then upload them on a different computer.

**Comment by comatory** [comment]
I see that’s good to know. Any plans on creating a sync service or is this out of scope / purpose of the app? ( I really like how accessible it is )

**Comment by Thibaut** [comment]
> Any plans on creating a sync service or is this out of scope / purpose of the app?

No plans. A sync service would require user authentication and a database (to store credentials and settings), both of which I want to avoid. The lack of those things contributes to making the app fast, accessible, secure, easier to maintain, cheap to host, and void of commercial interests (which matters to me for various reasons).

I would rather browser extensions fill the gap here. All settings (incl. doc selection) are stored in cookies, so if you sync those, you should be good to do. [1]

[1]: just realized that you won't be completely good to go, because documentations won't be downloaded (for offline mode) automatically after they're enabled through a cookie sync, and syncing IndexedDB data is not possible. Opened #711 for this.

**Comment by judy** [comment]
I use a ton of symbolic links for things like dotfiles (check out [mackup](https://github.com/lra/mackup)) to keep application settings in sync. I planned to explore doing this for devdocs, but haven't gotten around to it yet. I don't know how the preferences are stored locally; might be an option for @comatory ?

**Comment by comatory** [comment]
@judy yeah I could do that too, it'd work but too much hassle for me and I was hoping for native integration.
