### ISSUE TITLE
Generating documentation fails with 'Failed!'

### ISSUE THREAD

**Issue by etabakov** [Thibaut/devdocs#713]
I try to generate a new documentation. The `thor docs:generate` command goes to 100%, after that I get a 'Failed!' message and no further errors or hint what might be wrong. I tried with --verbose and --debug and the output is the same: 

`[#############################################################################################################################################################################################################################] [493/493] [100.00%] [01:15] [00:00] [  6.50/s]Failed!`

Can you help me troubleshoot this? I'm running on macOS High Sierra. The scraper I'm trying to add looks like this:

```
module Docs
  class Nativescript < UrlScraper
    self.name = 'Nativescript'
    self.release = '3.3.0'
    self.base_url = 'https://docs.nativescript.org'
    self.links = {
      home: 'https://www.nativescript.org/',
      code: 'https://github.com/nativescript/nativescript'
    }

    options[:attribution] = <<-HTML
      Test
    HTML
  end
end
```

Thank you!

**Comment by Thibaut** [comment]
Hey - this is because you haven't added an [`EntriesFilter`](https://github.com/Thibaut/devdocs/wiki/Filter-Reference#entriesfilter) to the scraper, so by the time it's done scraping, no entries (search/page data) have been created. I.e. the doc is empty.

You'll also need a [`CleanHtmlFilter`](https://github.com/Thibaut/devdocs/wiki/Filter-Reference#cleanhtmlfilter) to clean up the markup. See the existing scrapers for examples.

I'll see if I can improve the error message.
