### ISSUE TITLE
Add ReactiveX library for JavaScript (RxJS) docs

### ISSUE THREAD

**Issue by perception30** [Thibaut/devdocs#729]
RxJS is a library for reactive programming using Observables, to make it easier to compose asynchronous or callback-based code. This project is a rewrite of Reactive-Extensions/RxJS with better performance, better modularity, better debuggable call stacks, while staying mostly backwards compatible, with some breaking changes that reduce the API surface.

http://reactivex.io/rxjs/

**Comment by j-f1** [comment]
According to [the contributing guide](https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations), @Thibaut would like you to use the 👍 Vote button on [the RxJS card](https://trello.com/c/Fww4A1v4/238-rxjs) instead of opening an issue. If you know Ruby, you can add this yourself, since @Thibaut doesn’t have time to add many new docs these days.
