### ISSUE TITLE
change font and size

### ISSUE THREAD

**Issue by Abu3safeer** [Thibaut/devdocs#738]
Hello,
Is there anyway to change the font and the font size through settings?
I was about to use [Stylish](https://userstyles.org) but I wanted to make sure if there an exist option for that.

**Comment by Thibaut** [comment]
There isn't. All browsers should implement this natively, so I don't think we need a setting for it. The app is optimized for scaling well when zoom is adjusted (through the browser's zoom feature),

**Comment by Abu3safeer** [comment]
Thank you, didn't think of it this way, using browser zoom feature is better actually.

**Comment by kkinder** [comment]
It could be an issue with Epiphany, but actually DevDocs *isn't* obeying the system font settings. If you go into Settings and Universal Access and bump up the text size to "larger", absolutely nothing happens in DevDocs; it continues to display the original font size, even after a reboot.

In the Epiphany browser, there is no global font setting in Juno, so that's no help either.

The ultimate result is that DevDocs is pretty unesable if you're someone who needs bigger fonts.

**Comment by j-f1** [comment]
@kkinder Does Epiphany not have a zoom function?

**Comment by kkinder** [comment]
@j-f1 It does. But, it doesn't seem to have a way of setting the default zoom for every website.
