### ISSUE TITLE
Request : Can C# include?

### ISSUE THREAD

**Issue by thyeun** [Thibaut/devdocs#749]
i been using devdocs to search syntax about three months, but will it be possible include C# also?

due to that C# are among the popular programming language also.

Hope that C# can be include too, thank you so much.

**Comment by Thibaut** [comment]
Please read the [contributing guidelines](https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations).

**Comment by thyeun** [comment]
Sorry, i dont get what u mean by give me contributing guidelines link?

i'm just want to request will it be possible to include C#, due to that i can not find it inside devdocs

**Comment by Kaijiro** [comment]
What @Thibaut is telling is the following point : "Please don't open issues to request new documentations. Use the Trello board where everyone can vote."

When you opened your issue, you should have seen this "To request a new documentation, or an update of an existing documentation, go here:
  https://trello.com/b/6BmTulfx/devdocs-documentation"

Despite this warning you still posted this issue that is indeed not an issue but just a lack of comprehension of this repo rules.
So, your issue is being closed with no further explications. (Btw, Thibaut is closing tons of this kind of issues because people don't mind reading the comment in the issue template, so ...)
